/*
 * SPDX-FileCopyrightText: Copyright Corsinvest Srl
 * SPDX-License-Identifier: GPL-3.0-only
 */

using ClosedXML.Excel;

namespace Corsinvest.ProxmoxVE.Report;

public partial class ReportEngine
{
    private void AddCoverPage(XLWorkbook workbook)
    {
        var ws = workbook.Worksheets.Add("Summary");
        var row = 1;

        void Add(string value)
        {
            ws.Cell(row, 1).Value = value;
            ws.Cell(row, 1).Style.Font.SetBold(true);
            ws.Cell(row, 1).Style.Font.SetFontSize(14);
        }


        ws.Cell(row, 1).Value = "INFRASTRUCTURE REPORT";
        ws.Cell(row, 1).Style.Font.SetBold(true);
        ws.Cell(row, 1).Style.Font.SetFontSize(20);
        ws.Range(row, 1, row, 3).Merge();
        row += 2;

        Add("Report Information");
        row++;

        ws.Cell(row, 1).Value = "Generated:";
        ws.Cell(row, 2).Value = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
        row++;

        ws.Cell(row, 1).Value = "Application:";
        ws.Cell(row, 2).Value = $"cv4pve-report v{typeof(ReportEngine).Assembly.GetName().Version?.ToString(3)}";
        row += 2;

        Add("Filters Applied");
        row++;

        ws.Cell(row, 1).Value = "Nodes:";
        ws.Cell(row, 2).Value = settings.Node.Names;
        row++;

        ws.Cell(row, 1).Value = "VMs/Containers:";
        ws.Cell(row, 2).Value = settings.Guest.Ids;
        row++;

        ws.Cell(row, 1).Value = "Storages:";
        ws.Cell(row, 2).Value = settings.Storage.Names;
        row++;

        ws.Cell(row, 1).Value = "Node RRD TimeFrame:";
        ws.Cell(row, 2).Value = settings.Node.RrdData.TimeFrame.ToString();
        row++;

        ws.Cell(row, 1).Value = "Node RRD Consolidation:";
        ws.Cell(row, 2).Value = settings.Node.RrdData.Consolidation.ToString();
        row++;

        ws.Cell(row, 1).Value = "Guest RRD TimeFrame:";
        ws.Cell(row, 2).Value = settings.Guest.RrdData.TimeFrame.ToString();
        row++;

        ws.Cell(row, 1).Value = "Guest RRD Consolidation:";
        ws.Cell(row, 2).Value = settings.Guest.RrdData.Consolidation.ToString();
        row++;

        ws.Cell(row, 1).Value = "Storage RRD TimeFrame:";
        ws.Cell(row, 2).Value = settings.Storage.RrdData.TimeFrame.ToString();
        row++;

        ws.Cell(row, 1).Value = "Storage RRD Consolidation:";
        ws.Cell(row, 2).Value = settings.Storage.RrdData.Consolidation.ToString();
        row += 2;

        Add("Contents");
        row++;

        var sections = new[]
        {
            ("Cluster",  "Cluster overview, users, roles, ACL, firewall, backup, replication"),
            ("Storages", "Storage list with links to details"),
            ("Nodes",    "Node list with links to details"),
            ("Vms",      "VM/Container list with links to details"),
        };

        foreach (var (sheetName, description) in sections)
        {
            ws.Cell(row, 1).Value = sheetName;
            ws.Cell(row, 1).Style.Font.SetUnderline(XLFontUnderlineValues.Single);
            ws.Cell(row, 1).Style.Font.SetFontColor(XLColor.Blue);
            ws.Cell(row, 1).SetHyperlink(new XLHyperlink($"'{sheetName}'!A1"));
            ws.Cell(row, 2).Value = description;
            row++;
        }

        row += 2;
        ws.Cell(row, 1).Value = "Generated by";
        ws.Cell(row, 1).Style.Font.SetItalic(true);
        ws.Cell(row, 1).Style.Font.SetFontColor(XLColor.Gray);
        ws.Cell(row, 2).Value = "cv4pve-report";
        ws.Cell(row, 2).SetHyperlink(new XLHyperlink("https://github.com/Corsinvest/cv4pve-report"));
        ws.Cell(row, 2).Style.Font.SetFontColor(XLColor.Blue);
        ws.Cell(row, 2).Style.Font.SetUnderline(XLFontUnderlineValues.Single);
        ws.Cell(row, 2).Style.Font.SetItalic(true);

        ws.Column(1).Width = 20;
        ws.Column(2).Width = 60;
    }
}
