/*
 * SPDX-FileCopyrightText: Copyright Corsinvest Srl
 * SPDX-License-Identifier: GPL-3.0-only
 */

using ClosedXML.Excel;
using Corsinvest.ProxmoxVE.Api;
using Corsinvest.ProxmoxVE.Api.Extension;
using Corsinvest.ProxmoxVE.Api.Shared.Models.Cluster;
using System.Text.RegularExpressions;

namespace Corsinvest.ProxmoxVE.Report;

/// <summary>Report engine for Proxmox VE infrastructure.</summary>
public partial class ReportEngine(PveClient client, Settings settings)
{
    private IProgress<ReportProgress>? _progress;
    private readonly Dictionary<string, string> _sheetLinks = [];

    private string? GetSheetName(ClusterResourceType type, params string[] values)
        => _sheetLinks.TryGetValue(SheetLinkKey(type, values), out var name)
            ? name
            : null;

    internal static string SheetLinkKey(ClusterResourceType type, params string[] values)
        => $"{type.ToString().ToLowerInvariant()}:{values.JoinAsString(":")}";

    private async Task BuildSheetLinksAsync()
    {
        foreach (var item in await client.Cluster.Resources.GetAsync())
        {
            switch (item.ResourceType)
            {
                case ClusterResourceType.Node:
                    _sheetLinks[SheetLinkKey(ClusterResourceType.Node, item.Node)] = $"Node {item.Node}";
                    break;

                case ClusterResourceType.Vm:
                    _sheetLinks[SheetLinkKey(ClusterResourceType.Vm, item.VmId.ToString())] = $"VM {item.VmId}";
                    break;

                case ClusterResourceType.Storage:
                    _sheetLinks[SheetLinkKey(ClusterResourceType.Storage, item.Node, item.Storage)] = $"Storage {item.Node} - {item.Storage}";
                    break;
            }
        }
    }

    /// <summary>Generates the Excel report and saves it to the specified file path.</summary>
    public async Task<string> GenerateAsync(string fileName, IProgress<ReportProgress>? progress = null)
    {
        _progress = progress;
        await GenerateExcelAsync(fileName);
        return fileName;
    }

    private void ReportGlobal(string step)
        => _progress?.Report(new ReportProgress { Step = step });

    private async Task GenerateExcelAsync(string fileName)
    {
        ReportGlobal("Init");
        await BuildSheetLinksAsync();

        using var workbook = new XLWorkbook();
        ConfigureWorkbook(workbook);

        ReportGlobal("Cover");
        AddCoverPage(workbook);

        ReportGlobal("Cluster");
        await AddClusterDataAsync(workbook);

        ReportGlobal("Storages");
        await AddStoragesDataAsync(workbook);

        ReportGlobal("Nodes");
        await AddNodesDataAsync(workbook);

        ReportGlobal("Vms");
        await AddVmsDataAsync(workbook);

        ReportGlobal("Saving");
        workbook.SaveAs(fileName);
    }

    private static double ToGB(double bytes) => Math.Round(bytes / 1024 / 1024 / 1024, 2);
    private static double ToMB(double bytes) => Math.Round(bytes / 1024 / 1024, 2);

    private static bool CheckNames(string names, string name)
    {
        if (string.IsNullOrWhiteSpace(names) || names.Equals("@all", StringComparison.OrdinalIgnoreCase)) { return true; }

        foreach (var token in names.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            if (!token.Contains('*'))
            {
                if (token.Equals(name, StringComparison.OrdinalIgnoreCase)) { return true; }
            }
            else
            {
                if (token == "*") { return true; }
                var pattern = "^" + Regex.Escape(token).Replace(@"\*", ".*") + "$";
                if (Regex.IsMatch(name, pattern, RegexOptions.IgnoreCase)) { return true; }
            }
        }

        return false;
    }

    private static void ConfigureWorkbook(XLWorkbook workbook)
    {
        workbook.Author = "cv4pve-report";
        workbook.Properties.Author = "cv4pve-report Corsinvest Srl";
        workbook.Properties.Title = "Infrastructure Report";
        workbook.Properties.Subject = "cv4pve-report System Report";
        workbook.Properties.Category = "IT Infrastructure";
        workbook.Properties.Comments = "Automated report generated by cv4pve-report for Proxmox VE";
        workbook.Properties.Company = "Corsinvest Srl";
    }

    private static void AddFirewallRules(SheetWriter sw, IEnumerable<Api.Shared.Models.Common.FirewallRule> rules)
        => sw.CreateTable("Firewall Rules",
                          rules.Select(r => new
                          {
                              r.Positon,
                              r.Type,
                              r.Action,
                              r.Enable,
                              r.Source,
                              r.Dest,
                              r.Protocol,
                              r.DestinationPort,
                              r.SourcePort,
                              r.Comment
                          }));
}
