/*
 * SPDX-FileCopyrightText: Copyright Corsinvest Srl
 * SPDX-License-Identifier: GPL-3.0-only
 */

using ClosedXML.Excel;

namespace Corsinvest.ProxmoxVE.Report.Writers.Xlsx;

internal sealed partial class XlsxReportWriter
{
    public void WriteCoverPage(Settings settings, IEnumerable<SectionStat> stats)
    {
        var ws = _workbook.Worksheets.Add("Summary");
        var row = 1;

        void AddHeader(string value)
        {
            ws.Cell(row, 1).Value = value;
            ws.Cell(row, 1).Style.Font.SetBold(true);
            ws.Cell(row, 1).Style.Font.SetFontSize(14);
            row++;
        }

        void AddKV(string key, string value)
        {
            ws.Cell(row, 1).Value = key;
            ws.Cell(row, 2).Value = value;
            row++;
        }

        ws.Cell(row, 1).Value = "INFRASTRUCTURE REPORT";
        ws.Cell(row, 1).Style.Font.SetBold(true);
        ws.Cell(row, 1).Style.Font.SetFontSize(20);
        ws.Range(row, 1, row, 3).Merge();
        row += 2;

        AddHeader("Report Information");

        AddKV("Generated:", DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
        AddKV("Application:", $"{_info.ApplicationName} v{_info.ApplicationVersion}");
        row++;

        AddHeader("Filters Applied");

        AddKV("Nodes:", settings.Node.Names);
        AddKV("VMs/Containers:", settings.Guest.Ids);

        if (settings.Node.RrdData.Enabled)
        {
            AddKV("Node RRD TimeFrame:", settings.Node.RrdData.TimeFrame.ToString());
            AddKV("Node RRD Consolidation:", settings.Node.RrdData.Consolidation.ToString());
        }

        if (settings.Guest.RrdData.Enabled)
        {
            AddKV("Guest RRD TimeFrame:", settings.Guest.RrdData.TimeFrame.ToString());
            AddKV("Guest RRD Consolidation:", settings.Guest.RrdData.Consolidation.ToString());
        }

        if (settings.Storage.RrdData.Enabled)
        {
            AddKV("Storage RRD TimeFrame:", settings.Storage.RrdData.TimeFrame.ToString());
            AddKV("Storage RRD Consolidation:", settings.Storage.RrdData.Consolidation.ToString());
        }

        AddHeader("Contents");

        ws.Cell(row, 1).Value = "Sheet";
        ws.Cell(row, 2).Value = "Description";
        ws.Cell(row, 3).Value = "Count";
        ws.Cell(row, 4).Value = "Duration";
        foreach (var col in new[] { 1, 2, 3, 4 })
        {
            ws.Cell(row, col).Style.Font.SetBold(true);
            ws.Cell(row, col).Style.Fill.SetBackgroundColor(XLColor.LightGray);
        }
        row++;

        var statsList = stats.ToList();

        foreach (var stat in statsList)
        {
            ws.Cell(row, 1).Value = stat.Name;
            ws.Cell(row, 1).Style.Font.SetUnderline(XLFontUnderlineValues.Single);
            ws.Cell(row, 1).Style.Font.SetFontColor(XLColor.Blue);

            var actualSheet = _workbook.Worksheets.FirstOrDefault(s => s.Name.StartsWith(stat.Name[..Math.Min(stat.Name.Length, MaxSheetNameLength)]))?.Name ?? stat.Name;
            ws.Cell(row, 1).SetHyperlink(new XLHyperlink($"'{actualSheet}'!A1"));
            ws.Cell(row, 2).Value = stat.Description;
            ws.Cell(row, 3).Value = stat.Count;
            ws.Cell(row, 4).Value = stat.Duration.TotalSeconds < 60
                ? $"{stat.Duration.TotalSeconds:F1}s"
                : $"{stat.Duration.TotalMinutes:F1}m";

            row++;
        }

        var totalDuration = TimeSpan.FromSeconds(statsList.Sum(s => s.Duration.TotalSeconds));
        ws.Cell(row, 1).Value = "Total";
        ws.Cell(row, 1).Style.Font.SetBold(true);
        ws.Cell(row, 4).Value = totalDuration.TotalSeconds < 60
            ? $"{totalDuration.TotalSeconds:F1}s"
            : $"{totalDuration.TotalMinutes:F1}m";
        ws.Cell(row, 4).Style.Font.SetBold(true);
        row += 2;

        ws.Cell(row, 1).Value = "Generated by";
        ws.Cell(row, 1).Style.Font.SetItalic(true);
        ws.Cell(row, 1).Style.Font.SetFontColor(XLColor.Gray);
        ws.Cell(row, 2).Value = _info.ApplicationName;
        ws.Cell(row, 2).SetHyperlink(new XLHyperlink(_info.ApplicationUrl));
        ws.Cell(row, 2).Style.Font.SetFontColor(XLColor.Blue);
        ws.Cell(row, 2).Style.Font.SetUnderline(XLFontUnderlineValues.Single);
        ws.Cell(row, 2).Style.Font.SetItalic(true);

        ws.Columns(1, 4).AdjustToContents();
    }
}
