/*
 * SPDX-FileCopyrightText: Copyright Corsinvest Srl
 * SPDX-License-Identifier: GPL-3.0-only
 */

using ClosedXML.Excel;

namespace Corsinvest.ProxmoxVE.Report.Writers.Xlsx;

/// <summary>
/// Top-level writer that builds an Excel workbook through ISectionWriter calls.
/// Produces a single .xlsx on SaveAsync.
/// </summary>
internal sealed partial class XlsxReportWriter : IReportWriter
{
    private readonly XLWorkbook _workbook = new();
    private readonly Dictionary<string, string> _sheetLinks = [];
    private readonly Dictionary<string, int> _usedSheetNames = [];

    public IDictionary<string, string> Links => _sheetLinks;

    /// <summary>Underlying workbook for Excel-specific callers (cover page, etc.).</summary>
    public XLWorkbook Workbook => _workbook;

    /// <summary>Excel hard limit on sheet name length.</summary>
    public const int MaxSheetNameLength = 31;

    /// <summary>No-op for Excel: the SVG is written next to the .xlsx by the caller.</summary>
    public void SetNetworkDiagram(string svg) { /* no-op */ }

    public void SetMetadata(ReportInfo info)
    {
        _workbook.Author = info.ApplicationName;
        _workbook.Properties.Author = info.ApplicationName;
        _workbook.Properties.Title = "Infrastructure Report";
        _workbook.Properties.Subject = $"{info.ApplicationName} v{info.ApplicationVersion} System Report";
        _workbook.Properties.Category = "IT Infrastructure";
        _workbook.Properties.Comments = $"Automated report generated by {info.ApplicationName} for Proxmox VE";
        _workbook.Properties.Company = "Corsinvest Srl";
    }

    public ISectionWriter AddSection(string name)
    {
        var safeName = SafeSheetName(name);

        // Update any sheetLink that still points to the logical name to the
        // actual safe name (mirrors the existing behaviour in ReportEngine).
        foreach (var key in _sheetLinks.Where(kv => kv.Value == name).Select(kv => kv.Key).ToList())
        {
            _sheetLinks[key] = safeName;
        }

        var ws = _workbook.Worksheets.Add(safeName);
        var sheet = new SheetWriter(ws, _sheetLinks);
        return new XlsxSectionWriter(sheet);
    }

    public Task SaveAsync(Stream stream)
    {
        ReorderSheets();
        _workbook.SaveAs(stream);
        return Task.CompletedTask;
    }

    public void Dispose() => _workbook.Dispose();

    private string SafeSheetName(string candidate)
    {
        const int MaxSheetNameLength = 31;
        var name = candidate.Length <= MaxSheetNameLength ? candidate : candidate[..MaxSheetNameLength];
        if (!_usedSheetNames.TryGetValue(name, out var count))
        {
            _usedSheetNames[name] = 1;
            return name;
        }
        count++;
        _usedSheetNames[name] = count;
        var suffix = $"_{count}";
        return name[..Math.Min(name.Length, MaxSheetNameLength - suffix.Length)] + suffix;
    }

    private void ReorderSheets()
    {
        var pos = 1;

        void Place(IEnumerable<IXLWorksheet> sheets)
        {
            foreach (var ws in sheets) { ws.Position = pos++; }
        }

        void PlaceByPrefix(string prefix) =>
            Place(_workbook.Worksheets.Where(a => a.Name == prefix
                                                    || a.Name.StartsWith(prefix + " ")
                                                    || a.Name.StartsWith(prefix + "_")));

        void PlaceVmPrefix(string prefix) =>
            Place(_workbook.Worksheets
                          .Where(w => w.Name.StartsWith(prefix + " "))
                          .OrderBy(w => int.TryParse(w.Name[(prefix.Length + 1)..], out var n) ? n : int.MaxValue));

        PlaceByPrefix("Summary");
        PlaceByPrefix("Cluster");
        PlaceByPrefix("Nodes");
        PlaceByPrefix("VMs");
        PlaceByPrefix("Containers");
        PlaceByPrefix("Disks");
        PlaceByPrefix("Partitions");
        PlaceByPrefix("Snapshots");
        PlaceByPrefix("Network");
        PlaceByPrefix("Storages");
        PlaceByPrefix("Storage Content");
        PlaceByPrefix("Backups");
        PlaceByPrefix("Firewall");
        PlaceByPrefix("Replication");
        PlaceByPrefix("RRD Nodes");
        PlaceByPrefix("RRD Storage");
        PlaceByPrefix("RRD Guests");
        PlaceByPrefix("Syslog");
        PlaceByPrefix("Node");
        PlaceVmPrefix("VM");
        PlaceVmPrefix("CT");
    }
}
