/*
 * SPDX-FileCopyrightText: Copyright Corsinvest Srl
 * SPDX-License-Identifier: GPL-3.0-only
 */

using System.IO.Compression;
using ClosedXML.Excel;

namespace Corsinvest.ProxmoxVE.Report.Writers.Xlsx;

internal sealed partial class XlsxReportWriter : IReportWriter
{
    private readonly XLWorkbook _workbook = new();
    private readonly UniqueNameAllocator _sheetNames = new(StringComparer.OrdinalIgnoreCase);
    private readonly ReportInfo _info;
    private string? _networkDiagramSvg;

    public Dictionary<string, string> Links { get; } = [];

    /// <summary>Excel hard limit on sheet name length.</summary>
    public const int MaxSheetNameLength = 31;

    public XlsxReportWriter(ReportInfo info)
    {
        _info = info;
        _workbook.Author = info.ApplicationName;
        _workbook.Properties.Author = info.ApplicationName;
        _workbook.Properties.Title = "Infrastructure Report";
        _workbook.Properties.Subject = $"{info.ApplicationName} v{info.ApplicationVersion} System Report";
        _workbook.Properties.Category = "IT Infrastructure";
        _workbook.Properties.Comments = $"Automated report generated by {info.ApplicationName} for Proxmox VE";
        _workbook.Properties.Company = "Corsinvest Srl";
    }

    public void SetNetworkDiagram(string svg) => _networkDiagramSvg = svg;

    public ISectionWriter AddSection(SectionId id)
    {
        var sheetName = id switch
        {
            SectionId.Node n => $"Node {n.Hostname}",
            SectionId.Vm v => $"VM {v.Id}",
            SectionId.Container c => $"CT {c.Id}",
            _ => id.Key,
        };
        var safeName = SafeSheetName(sheetName);

        // Pre-existing Links pointing at the logical name follow the truncated safe name.
        foreach (var key in Links.Where(kv => kv.Value == id.Key).Select(kv => kv.Key).ToList())
        {
            Links[key] = safeName;
        }

        var ws = _workbook.Worksheets.Add(safeName);
        var sheet = new SheetWriter(ws, Links);

        if (LinkKey.ForSection(id.Key) is { } sectionKey) { Links[sectionKey] = safeName; }

        return new XlsxSectionWriter(sheet);
    }

    public async Task SaveAsync(Stream stream)
    {
        ReorderSheets();

        using var zip = new ZipArchive(stream, ZipArchiveMode.Create, leaveOpen: true);

        var xlsxEntry = zip.CreateEntry("report.xlsx", CompressionLevel.Optimal);
        await using (var xlsxStream = xlsxEntry.Open())
        {
            _workbook.SaveAs(xlsxStream);
        }

        await ZipHelpers.WriteNetworkDiagramAsync(zip, _networkDiagramSvg);
    }

    public void Dispose() => _workbook.Dispose();

    private string SafeSheetName(string candidate) => _sheetNames.Allocate(candidate, MaxSheetNameLength);

    private void ReorderSheets()
    {
        var pos = 1;

        void Place(IEnumerable<IXLWorksheet> sheets)
        {
            foreach (var ws in sheets) { ws.Position = pos++; }
        }

        void PlaceByPrefix(string prefix) =>
            Place(_workbook.Worksheets.Where(a => a.Name == prefix
                                                    || a.Name.StartsWith(prefix + " ")
                                                    || a.Name.StartsWith(prefix + "_")));

        void PlaceVmPrefix(string prefix) =>
            Place(_workbook.Worksheets
                          .Where(w => w.Name.StartsWith(prefix + " "))
                          .OrderBy(w => int.TryParse(w.Name[(prefix.Length + 1)..], out var n) ? n : int.MaxValue));

        void PlaceExact(string name) =>
            Place(_workbook.Worksheets.Where(a => a.Name == name));

        PlaceByPrefix("Summary");
        PlaceByPrefix("Issues");
        PlaceExact("Cluster");
        PlaceByPrefix("Storages");
        PlaceByPrefix("Nodes");
        PlaceByPrefix("VMs");
        PlaceByPrefix("Containers");
        PlaceByPrefix("Network");
        PlaceByPrefix("Storage Content");
        PlaceByPrefix("Backups");
        PlaceByPrefix("Disks");
        PlaceByPrefix("Partitions");
        PlaceByPrefix("Snapshots");
        PlaceByPrefix("Firewall");
        PlaceByPrefix("Replication");
        PlaceByPrefix("RRD Nodes");
        PlaceByPrefix("RRD Storage");
        PlaceByPrefix("RRD Guests");
        PlaceByPrefix("Syslog");
        PlaceExact("Cluster Access");
        PlaceExact("Cluster SDN");
        PlaceExact("Cluster HA");
        PlaceExact("Cluster Pools");
        PlaceExact("Cluster Log");
        PlaceExact("Cluster Tasks");
        PlaceByPrefix("Node");
        PlaceVmPrefix("VM");
        PlaceVmPrefix("CT");
    }
}
